### PR TITLE
Fix Sony SO-03L

### LINKED ISSUE #45: SO-03L has two same resolution event device
Hi there, first thank you so much make this great tool.

when use [SO-03L](https://www.nttdocomo.co.jp/product/smart_phone/so03l/), this device has a side detect function, if we run `adb shell getevent` , we will see the event4(sec_touchscreen_side) and event3(sec_touchscreen) 

```
add device 1: /dev/input/event8
  name:     "sm8150-tavil-snd-card Button Jack"
add device 2: /dev/input/event7
  name:     "sm8150-tavil-snd-card Headset Jack"
add device 3: /dev/input/event6
  name:     "AMS TCS3490 Sensor"
add device 4: /dev/input/event5
  name:     "bu520x1nvx"
add device 5: /dev/input/event4
  name:     "sec_touchscreen_side"
add device 6: /dev/input/event3
  name:     "sec_touchscreen"
add device 7: /dev/input/event2
  name:     "gpio-keys"
add device 8: /dev/input/event1
  name:     "SOMC Charger Removal"
add device 9: /dev/input/event0
  name:     "qpnp_pon"
```
and those two event has the same resolution, the autodetection method  will get same score for those two screen, it will chose the event4 which is the wrong one. 

Currently I add config for openstf  when starting minitouch on SO-03L add extra cmd '-d /dev/input/event3', and it works.

any suggestion that we can do to about the autodetection method ?
have anyone ever meet a device that has more than one event device that has same score?

### PR DESCRIPTION
**Pull request by huanglizhuo**
fix #45 , decrease the score by 1 if device name contains '_side'

### CODE REVIEW

**Comment by huanglizhuo** [comment]
@sorccu  when you got time you can test it. I tried it on my local stf (about 120 devices) it's good

File: jni/minitouch/minitouch.c [hunk 1]
```diff
@@ -152,8 +152,11 @@ static int consider_device(const char* devpath, internal_state_t* state)
   }
 
   // For Blackberry devices, see above.
+  // Also some device like SO-03L it has two touch device, one is for touch
```
Comment (koral--) [inline jni/minitouch/minitouch.c]:
```suggestion
  // Also some device like SO-03L it has two touch devices, one is for touch
```

**Review by koral-- — APPROVED** [review]
LGTM

File: jni/minitouch/minitouch.c (hunk 1 above)
Comment (huanglizhuo) [reply jni/minitouch/minitouch.c]: thanks, fixed

**Comment by sorccu** [comment]
Thanks!
